image: node:lts-alpine

stages:
  - test

default:
  before_script:
    - npm i -g lerna
    - lerna bootstrap

server-unit-tests:
  stage: test
  script:
    - cd packages/server
    - npm run test:cov
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

client-unit-tests:
  stage: test
  script:
    - cd packages/client
    - npm run test:cov
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'